stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main
