#!/usr/bin/env python3
"""Fit cross-model parameter maps using manifold mean/variance matching.

The script consumes `magnetization_summary.csv` generated by
`ising_magnetization_compare.py`, builds model manifolds indexed by
(model, J, h, T), and finds the best matching target parameter point for each
source parameter point by minimizing weighted trajectory distance over time.

It writes:
1) a row-wise matched map CSV (source -> best target + error), and
2) optional affine coefficients JSON approximating the mapping.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

Series = Dict[int, Tuple[float, float]]  # t -> (mean_m, var_m)
ParamPoint = Tuple[float, float, float]  # (J, h, T)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit parameter map phi_{i->j} from manifold summaries.")
    parser.add_argument("--summary-csv", default="python_demos/magnetization_summary.csv")
    parser.add_argument("--source-model", default="model_1")
    parser.add_argument("--target-model", default="model_2")
    parser.add_argument("--mean-weight", type=float, default=1.0)
    parser.add_argument("--var-weight", type=float, default=0.3)
    parser.add_argument("--output-map", default="python_demos/parameter_map.csv")
    parser.add_argument("--output-affine", default="python_demos/parameter_map_affine.json")
    return parser.parse_args()


def load_manifold(summary_csv: Path) -> Dict[Tuple[str, ParamPoint], Series]:
    manifold: Dict[Tuple[str, ParamPoint], Series] = {}
    with summary_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            model = str(row["model"])
            point: ParamPoint = (float(row["coupling"]), float(row["field"]), float(row["temperature"]))
            t = int(row["t"])
            mean_m = float(row["mean_m"])
            var_m = float(row["var_m"])
            key = (model, point)
            if key not in manifold:
                manifold[key] = {}
            manifold[key][t] = (mean_m, var_m)
    return manifold


def series_distance(src: Series, dst: Series, mean_w: float, var_w: float) -> float:
    common_t = sorted(set(src.keys()) & set(dst.keys()))
    if not common_t:
        return float("inf")

    total = 0.0
    for t in common_t:
        src_mean, src_var = src[t]
        dst_mean, dst_var = dst[t]
        total += mean_w * (src_mean - dst_mean) ** 2 + var_w * (src_var - dst_var) ** 2
    return total / len(common_t)


def fit_nearest_neighbor_map(
    manifold: Dict[Tuple[str, ParamPoint], Series],
    source_model: str,
    target_model: str,
    mean_w: float,
    var_w: float,
) -> List[Dict[str, float]]:
    source_points = [point for (model, point) in manifold.keys() if model == source_model]
    target_points = [point for (model, point) in manifold.keys() if model == target_model]

    rows: List[Dict[str, float]] = []
    for source_point in sorted(set(source_points)):
        src_series = manifold[(source_model, source_point)]

        best_target = None
        best_error = float("inf")
        for target_point in set(target_points):
            dst_series = manifold[(target_model, target_point)]
            err = series_distance(src_series, dst_series, mean_w=mean_w, var_w=var_w)
            if err < best_error:
                best_error = err
                best_target = target_point

        assert best_target is not None
        rows.append(
            {
                "source_coupling": source_point[0],
                "source_field": source_point[1],
                "source_temperature": source_point[2],
                "target_coupling": best_target[0],
                "target_field": best_target[1],
                "target_temperature": best_target[2],
                "fit_error": best_error,
            }
        )
    return rows


def solve_linear_4x4(a: List[List[float]], b: List[float]) -> List[float]:
    """Solve Ax=b for 4x4 matrix A via Gauss-Jordan elimination."""

    n = 4
    aug = [row[:] + [rhs] for row, rhs in zip(a, b)]

    for col in range(n):
        pivot = col
        for r in range(col + 1, n):
            if abs(aug[r][col]) > abs(aug[pivot][col]):
                pivot = r
        aug[col], aug[pivot] = aug[pivot], aug[col]

        piv = aug[col][col]
        if abs(piv) < 1e-12:
            raise ValueError("Singular matrix during affine fit")
        for c in range(col, n + 1):
            aug[col][c] /= piv

        for r in range(n):
            if r == col:
                continue
            factor = aug[r][col]
            for c in range(col, n + 1):
                aug[r][c] -= factor * aug[col][c]

    return [aug[i][n] for i in range(n)]


def fit_affine_coefficients(match_rows: Sequence[Dict[str, float]]) -> Dict[str, List[float]]:
    """Fit target params as affine fn of [1, source_J, source_h, source_T]."""

    x_rows = [
        [1.0, row["source_coupling"], row["source_field"], row["source_temperature"]]
        for row in match_rows
    ]

    def normal_eq(y_key: str) -> List[float]:
        xtx = [[0.0 for _ in range(4)] for _ in range(4)]
        xty = [0.0 for _ in range(4)]
        for x, row in zip(x_rows, match_rows):
            y = row[y_key]
            for i in range(4):
                xty[i] += x[i] * y
                for j in range(4):
                    xtx[i][j] += x[i] * x[j]
        return solve_linear_4x4(xtx, xty)

    return {
        "target_coupling": normal_eq("target_coupling"),
        "target_field": normal_eq("target_field"),
        "target_temperature": normal_eq("target_temperature"),
    }


def write_map_csv(path: Path, rows: Iterable[Dict[str, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "source_coupling",
        "source_field",
        "source_temperature",
        "target_coupling",
        "target_field",
        "target_temperature",
        "fit_error",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_affine_json(path: Path, coeffs: Dict[str, List[float]], source_model: str, target_model: str) -> None:
    payload = {
        "source_model": source_model,
        "target_model": target_model,
        "features": ["bias", "source_coupling", "source_field", "source_temperature"],
        "coefficients": coeffs,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def main() -> None:
    args = parse_args()
    manifold = load_manifold(Path(args.summary_csv))

    match_rows = fit_nearest_neighbor_map(
        manifold=manifold,
        source_model=args.source_model,
        target_model=args.target_model,
        mean_w=args.mean_weight,
        var_w=args.var_weight,
    )
    write_map_csv(Path(args.output_map), match_rows)

    coeffs = fit_affine_coefficients(match_rows)
    write_affine_json(Path(args.output_affine), coeffs, args.source_model, args.target_model)

    mean_err = sum(row["fit_error"] for row in match_rows) / max(1, len(match_rows))
    print(f"Wrote nearest-neighbor map to {args.output_map}")
    print(f"Wrote affine approximation to {args.output_affine}")
    print(f"Mean fit error: {mean_err:.6f} across {len(match_rows)} source points")


if __name__ == "__main__":
    main()
